### ISSUE TITLE
can not send the message to kafka

### ISSUE THREAD

**Issue by Fionn88** [Fionn88/Log-Agent#1]
1. kafka 和 zookeeper 是用 Docker Run 架設起來，以下為 docker run command
```
docker network create app-tier --driver bridge

docker run -d --name zookeeper --network app-tier -p 2181:2181 jplock/zookeeper

docker run -d --name kafka --link zookeeper --network app-tier -p 7203:7203 -p 9092:9092 -e KAFKA_ADVERTISED_HOST_NAME=zookeeper -e ZOOKEEPER_IP=zookeeper ches/kafka
```

2. go run main.go 接著 input 內容到 my.log 
```
WARN[0007] send message failed,kafka server: In the middle of a leadership election, there is currently no leader for this partition and hence it is unavailable for writes.
```

3. kafka 的 log
```
[2023-09-21 06:51:34,199] INFO Topic creation {"version":1,"partitions":{"0":[0]}} (kafka.admin.AdminUtils$)
[2023-09-21 06:51:34,213] INFO [KafkaApi-0] Auto creation of topic web_log with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
```

- Kafka ping zookeeper
<img width="791" alt="截圖 2023-09-21 下午4 22 24" src="https://github.com/Fionn88/Log-Agent/assets/56747201/9d25bf49-1eb6-4f13-bde7-85f222ee4f9c">

- Zookeeper ping kafka
<img width="703" alt="截圖 2023-09-21 下午4 23 33" src="https://github.com/Fionn88/Log-Agent/assets/56747201/f5cc3ce3-5486-4ec3-95e1-9c86a6a7c018">

**Comment by Fionn88** [comment]
- [Resolved](https://hub.docker.com/r/bitnami/kafka)
```
curl -sSL https://raw.githubusercontent.com/bitnami/containers/main/bitnami/kafka/docker-compose.yml > docker-compose.yml
docker-compose up -d
```

**Comment by Fionn88** [comment]
```
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
volumes:
  kafka_data:
    driver: local
```
